default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: password
  host: db

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { "chat_system" } %>

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_TEST_DATABASE") { "testdb" } %>

production:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { "chat_system_production" } %>
